dubbo:
  application:
    name: civism-gateway
  registry:
    address: 192.168.100.240:2181
    check: true
    protocol: zookeeper

zookeeper:
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 60000
  address: 192.168.100.240:2181